name: Release Notice
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dump Github context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Send custom JSON data to Discord
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL_STAGE }}
          nodetail: true
          title: New ${{ github.repository }} version ${{ github.event.release.tag_name }} published by ${{ github.actor }}
          description: |
            Description: ${{ github.workflow }}
            Version `23.11.4`
            https://github.com/Countly/countly-server/releases/tag/23.11.4
            Click [here](https://github.com/Countly/countly-server/blob/master/CHANGELOG.md) to view the change log!
