name: Discord Release Notice
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dump Github context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Set up environment variables
        run: |
         echo "DISCORD_WEBHOOK=https://discord.com/api/webhooks/1181122006507327498/5BaZ7Dv84xR4uKRO6vL9Veo_DIlA9SdZteSwn21nFea4O9CM6e04-TevwcTM9k7hRS7H" >> $GITHUB_ENV


      - name: Send custom JSON data to Discord
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: |
            {
              "repository": "${{ github.repository }}",
              "tag_name": "${{ github.event.release.tag_name }}",
              "actor": "${{ github.actor }}",
              "body": ${{ toJSON(github.event.release.body) }},
              "html_url": "${{ github.event.release.html_url }}"
            }
